[package]
name = "remote-shellcode-injection"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = {version = "0.3.9", features = ["winuser", "processthreadsapi", "memoryapi", "errhandlingapi", "synchapi", "handleapi", "tlhelp32", "psapi", "winerror", "winbase"]}